spring.application.name=cfl_project
#spring.datasource.url=jdbc:postgresql://localhost:5432/cfl-uat
spring.datasource.url=jdbc:postgresql://localhost:5432/cfl_app

spring.jpa.show-sql=true
spring.datasource.username=postgres
#spring.datasource.password=pgadmin
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-circular-references=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#server.port=9048

server.port=9048


Secret_String=


spring.mail.host=mapi.cms.co.in
spring.mail.port=587
spring.mail.username=startsmart@cms.co.in
spring.mail.password=Dell@2020

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.timeout=50000


logging.level.org.springframework.mail=DEBUG

spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.ssl.trust=*

#server.tomcat.relaxed-query-chars=|,{,},[,]

# Maximum file size (example: 20MB)
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Groq LLM Configuration
gemini.api.key=
gemini.api.url=https://api.groq.com/openai/v1/chat/completions
gemini.model=qwen/qwen3-32b

